name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Cache m2
        uses: actions/cache@v1.1.2
        with:
          path: /root/.m2
          key: test-root-m2-${{ hashFiles('deps.edn') }}
      - name: run test
        run: clojure -A:dev:test
