name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: v1-linux-deps-${{ hashFiles('deps.edn') }}
      - run: make test